print('Regis Kouatcho')
print('3214 Johnson St NE')
print('Minneapolis, MN 55418')
print()
print()
print("Don't fear!")
print("I'm here!")
print()
print()
print('Your assignment is to read "Hamlet" by tomorrow')
print()
